"""empty message

Revision ID: 20eb32f9b771
Revises: a934c4cc6bd3
Create Date: 2017-01-13 18:55:41.633971

"""

# revision identifiers, used by Alembic.
revision = '20eb32f9b771'
down_revision = 'a934c4cc6bd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('cat_over_dad', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('cat_over_dog', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('cat_over_nerd', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('cat_over_weird', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('dad_over_cat', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('dad_over_dog', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('dad_over_nerd', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('dad_over_weird', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('dog_over_cat', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('dog_over_dad', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('dog_over_nerd', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('dog_over_weird', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('nerd_over_cat', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('nerd_over_dad', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('nerd_over_dog', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('nerd_over_weird', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('weird_over_cat', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('weird_over_dad', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('weird_over_dog', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('weird_over_nerd', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'weird_over_nerd')
    op.drop_column('jokes', 'weird_over_dog')
    op.drop_column('jokes', 'weird_over_dad')
    op.drop_column('jokes', 'weird_over_cat')
    op.drop_column('jokes', 'nerd_over_weird')
    op.drop_column('jokes', 'nerd_over_dog')
    op.drop_column('jokes', 'nerd_over_dad')
    op.drop_column('jokes', 'nerd_over_cat')
    op.drop_column('jokes', 'dog_over_weird')
    op.drop_column('jokes', 'dog_over_nerd')
    op.drop_column('jokes', 'dog_over_dad')
    op.drop_column('jokes', 'dog_over_cat')
    op.drop_column('jokes', 'dad_over_weird')
    op.drop_column('jokes', 'dad_over_nerd')
    op.drop_column('jokes', 'dad_over_dog')
    op.drop_column('jokes', 'dad_over_cat')
    op.drop_column('jokes', 'cat_over_weird')
    op.drop_column('jokes', 'cat_over_nerd')
    op.drop_column('jokes', 'cat_over_dog')
    op.drop_column('jokes', 'cat_over_dad')
    ### end Alembic commands ###
